name: flutterfire_auth
description: A new Flutter package project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.18
  google_sign_in: ^5.3.1
  sign_in_with_apple: ^4.0.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.8
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
